laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group([
  'namespace' => 'Site'
], function(){

  Route::get('/', ['as' => 'home', 'uses' => 'Home\HomeController@getIndex']);
  Route::post('enviar-mensagem', ['as' => 'enviar-mensagem', 'uses' => 'Home\HomeController@postEnviarMensagem']);

  Route::get('a-companhia',              ['as' => 'a-companhia',                function(){ return view('site.pagina-texto.index', ['texto' => CiaTruks\Models\PaginaTexto::findBySlug('a-companhia')]); }]);
  Route::get('eventos',                  ['as' => 'eventos',                    function(){ return view('site.pagina-texto.index', ['texto' => CiaTruks\Models\PaginaTexto::findBySlug('eventos')]); }]);
  Route::get('centro-de-estudos',        ['as' => 'centro-de-estudos',          function(){ return view('site.pagina-texto.index', ['texto' => CiaTruks\Models\PaginaTexto::findBySlug('centro-de-estudos')]); }]);
  Route::get('contacao-de-historias',    ['as' => 'contacao-de-historias',      function(){ return view('site.pagina-texto.index', ['texto' => CiaTruks\Models\PaginaTexto::findBySlug('contacao-de-historias')]); }]);
  Route::get('contratacoes',             ['as' => 'contratacoes',               function(){ return view('site.pagina-texto.index', ['texto' => CiaTruks\Models\PaginaTexto::findBySlug('contratacoes')]); }]);
  Route::get('cursos-e-oficinas',        ['as' => 'cursos-e-oficinas',          function(){ return view('site.pagina-texto.index', ['texto' => CiaTruks\Models\PaginaTexto::findBySlug('cursos-e-oficinas')]); }]);
  Route::get('cursos-e-oficinas/{slug}', ['as' => 'cursos-e-oficinas.detalhes', 'uses' => 'CursosEOficinas\CursosEOficinasController@getIndex']);
  Route::get('agenda',                   ['as' => 'agenda',                     function(){ return view('site.agenda.index',       ['agendas' => CiaTruks\Models\Agenda::proximoPrimeiro()->datasFuturas()->get()]); }]);

  Route::get('espetaculos',        ['as' => 'espetaculos.index', 'uses' => 'Espetaculos\EspetaculosController@getIndex']);
  Route::get('espetaculos/{slug}', ['as' => 'espetaculos.detalhes', 'uses' => 'Espetaculos\EspetaculosController@getDetalhes']);
  Route::get('galeria-de-fotos',   ['as' => 'galeria-de-fotos', 'uses' => 'Galeria\GaleriaController@getIndex']);
  Route::get('videos',             ['as' => 'videos', 'uses' => 'Videos\VideosController@getIndex']);
  Route::get('videos/{slug}',      ['as' => 'videos.detalhes', 'uses' => 'Videos\VideosController@getDetalhes']);
  Route::get('noticias', ['as' => 'noticias.index', 'uses' => 'Noticias\NoticiasController@getIndex']);
  Route::get('noticias/{slug}', ['as' => 'noticias.detalhes', 'uses' => 'Noticias\NoticiasController@getDetalhes']);

  Route::get('criticas-e-materias', ['as' => 'criticas-e-materias', 'uses' => 'CriticasEMaterias\CriticasEMateriasController@getIndex']);
  Route::get('fale-conosco',  ['as' => 'fale-conosco', 'uses' => 'FaleConosco\FaleConoscoController@getIndex']);
  Route::post('fale-conosco', ['as' => 'fale-conosco.enviar', 'uses' => 'FaleConosco\FaleConoscoController@postEnviar']);

  Route::get('texto-ingles', ['as' => 'texto-ingles', function(){ return view('site.pagina-texto.index', ['texto' => CiaTruks\Models\TextoIngles::first()]); }]);
  Route::get('texto-espanhol', ['as' => 'texto-espanhol', function(){ return view('site.pagina-texto.index', ['texto' => CiaTruks\Models\TextoEspanhol::first()]); }]);

});

// Authentication routes
Route::get('painel/auth/login', ['as' => 'painel.login','uses' => 'Painel\Auth\AuthController@getLogin']);
Route::post('painel/auth/login', ['as' => 'painel.auth','uses' => 'Painel\Auth\AuthController@postLogin']);
Route::get('painel/auth/logout', ['as' => 'painel.logout','uses' => 'Painel\Auth\AuthController@getLogout']);

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Painel',
  'prefix' => 'painel'
], function() {

  Route::get('/', ['as' => 'painel.dashboard', 'uses' => function() {
    return view('painel.dashboard.index');
  }]);

  Route::post('gravar-ordem-registros', function(Request $request){
    if(Request::ajax()){

      $menu   = Input::get('data');
			$tabela = Input::get('tabela');

      for ($i = 0; $i < count($menu); $i++)
	    	DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));

    }
  });

  Route::resource('usuarios', 'Usuarios\UsuariosController');
  Route::resource('espetaculos', 'Espetaculos\EspetaculosController', ['except' => ['show']]);
  Route::resource('comentarios-da-imprensa', 'Espetaculos\ComentariosDaImprensaController', ['except' => ['show']]);

  Route::post('mensagens/toggle-aprovacao', ['as' => 'painel.mensagens.toggle-aprovacao', 'uses' => 'Mensagens\MensagensController@postAprovacaoToggle']);
  Route::resource('mensagens', 'Mensagens\MensagensController', ['only' => ['index', 'destroy']]);
  Route::resource('paginas-texto', 'PaginasTexto\PaginasTextoController', ['only' => ['index', 'edit', 'update']]);
  Route::resource('cursos-e-oficinas', 'CursosEOficinas\CursosEOficinasController', ['except' => ['show']]);
  Route::resource('criticas-e-materias', 'CriticasEMaterias\CriticasEMateriasController', ['except' => ['show']]);
  Route::resource('fale-conosco', 'FaleConosco\FaleConoscoController', ['only' => ['index', 'edit', 'update']]);
  Route::resource('destaques-home', 'DestaquesHome\DestaquesHomeController', ['only' => ['index', 'edit', 'update']]);
  Route::resource('chamadas-home', 'ChamadasHome\ChamadasHomeController', ['only' => ['index', 'edit', 'update']]);
  Route::resource('imagem-home', 'ImagemHome\ImagemHomeController', ['except' => ['show', 'create', 'store', 'destroy']]);
  Route::resource('texto-espanhol', 'OutrasLinguas\TextoEspanholController', ['only' => ['index', 'edit', 'update']]);
  Route::resource('texto-ingles', 'OutrasLinguas\TextoInglesController', ['only' => ['index', 'edit', 'update']]);
  Route::resource('agenda', 'Agenda\AgendaController', ['except' => ['show']]);
  Route::resource('noticias', 'Noticias\NoticiasController', ['except' => ['show']]);
  Route::resource('galerias-adicionais', 'GaleriasAdicionais\GaleriasAdicionaisController', ['except' => ['show']]);
  Route::resource('videos-adicionais', 'Videos\VideosAdicionaisController', ['except' => ['show', 'edit', 'update']]);

  Route::post('imagens/upload', 'Imagens\ImagensController@postUpload');
  Route::post('videos/consultar', 'Videos\VideosController@postConsultar');
  Route::post('videos/atualizar-titulo', 'Videos\VideosController@postAtualizarTitulo');

});

laravel/app/Http/Controllers/Painel/Agenda/AgendaController.php
<?php

namespace CiaTruks\Http\Controllers\Painel\Agenda;

use Illuminate\Http\Request;
use CiaTruks\Http\Controllers\Controller;

use View;

use CiaTruks\Models\Espetaculo;
use CiaTruks\Models\Agenda;

class AgendaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      if($request->filtro == 'futuras')
        $registros = Agenda::ordenado()->datasFuturas()->get();
      elseif($request->filtro == 'passadas')
        $registros = Agenda::ordenado()->datasPassadas()->get();
      else
        $registros = Agenda::ordenado()->get();

      return view('painel.agenda.index')->with(compact('registros'))->with('filtro', $request->filtro);
    }

    public function create(Request $request)
    {
      $espetaculos = Espetaculo::all();
      return view('painel.agenda.create', compact('espetaculos'));
    }

    public function store(Request $request)
    {
      $this->validate($request, [
      	'espetaculos_id' => 'required|exists:espetaculos,id',
        'data'           => 'required|date_format:d/m/Y',
    	]);

      $object = new Agenda;

      $object->espetaculos_id = $request->espetaculos_id;
      $object->data = $request->data;
      $object->horarios = $request->horarios;
      $object->texto = $request->texto;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Item da Agenda criado com sucesso.');

        return redirect()->route('painel.agenda.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao criar item da agenda! ('.$e->getMessage().')'));

      }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      $espetaculos = Espetaculo::all();
      return view('painel.agenda.edit')->with('registro', Agenda::find($id))
                                       ->with('espetaculos', $espetaculos);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
      	'espetaculos_id' => 'required|exists:espetaculos,id',
        'data'           => 'required|date_format:d/m/Y',
    	]);

      $object = Agenda::find($id);

      $object->espetaculos_id = $request->espetaculos_id;
      $object->data = $request->data;
      $object->horarios = $request->horarios;
      $object->texto = $request->texto;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Item da Agenda alterado com sucesso.');

        return redirect()->route('painel.agenda.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar item da agenda! ('.$e->getMessage().')'));

      }
    }

    public function destroy(Request $request, $id){
      $object = Agenda::find($id);
      $object->delete();

      $request->session()->flash('sucesso', 'Item da Agenda removido com sucesso.');

      return redirect()->route('painel.agenda.index');
    }

}

laravel/app/Http/Controllers/Painel/ChamadasHome/ChamadasHomeController.php
<?php

namespace CiaTruks\Http\Controllers\Painel\ChamadasHome;

use Illuminate\Http\Request;
use CiaTruks\Http\Controllers\Controller;

use View;

use CiaTruks\Models\ChamadaHome;

class ChamadasHomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
      $registros = ChamadaHome::ordenado()->get();

      return view('painel.chamadas-home.index')->with(compact('registros'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      return view('painel.chamadas-home.edit')->with('registro', ChamadaHome::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
        'titulo' => 'required',
      	'link'   => 'required'
    	]);

      $object = ChamadaHome::find($id);
      $object->titulo = $request->titulo;
      $object->texto = $request->texto;
      $object->link = $request->link;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Chamada alterada com sucesso.');

        return redirect()->route('painel.chamadas-home.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar chamada! ('.$e->getMessage().')'));

      }
    }

}

laravel/app/Http/Controllers/Painel/CriticasEMaterias/CriticasEMateriasController.php
<?php

namespace CiaTruks\Http\Controllers\Painel\CriticasEMaterias;

use Illuminate\Http\Request;
use CiaTruks\Http\Controllers\Controller;
use CiaTruks\Libs\Thumbs;

use View;

use CiaTruks\Models\CriticasEMaterias;

class CriticasEMateriasController extends Controller{

	public function index()
	{
		$registros = CriticasEMaterias::ordenado()->get();

		return view('painel.criticas-e-materias.index')->with(compact('registros'));
	}

	public function create()
	{
		return view('painel.criticas-e-materias.create');
	}

	public function store(Request $request)
	{
		$this->validate($request, [
      'titulo' => 'required',
			'data'   => 'required|date_format:d/m/Y',
			'imagem' => 'required|image'
  	]);

		$object = new CriticasEMaterias;

		$object->titulo = $request->titulo;
    $object->data = $request->data;

		$imagem = Thumbs::make('imagem', 900, null, 'criticas-e-materias/ampliadas/');
		if($imagem) $object->imagem = $imagem;

		Thumbs::make('imagem', 180, 180, 'criticas-e-materias/capas/');

		try {

			$object->save();

			$request->session()->flash('sucesso', 'Crítica criada com sucesso.');

			return redirect()->route('painel.criticas-e-materias.index');

		} catch (\Exception $e) {

			$request->flash();

			return back()->withErrors(array('Erro ao criar Crítica! ('.$e->getMessage().')'));

		}
	}

	public function edit($id)
	{
		$registro = CriticasEMaterias::find($id);

		return view('painel.criticas-e-materias.edit')->with(compact('registro'));
	}

	public function update(Request $request, $id)
	{
		$this->validate($request, [
      'titulo' => 'required',
			'data'   => 'required|date_format:d/m/Y',
			'imagem' => 'sometimes|image'
  	]);

		$object = CriticasEMaterias::find($id);

		$object->titulo = $request->titulo;
    $object->data = $request->data;

		$imagem = Thumbs::make('imagem', 900, null, 'criticas-e-materias/ampliadas/');
		if($imagem) $object->imagem = $imagem;

		Thumbs::make('imagem', 180, 180, 'criticas-e-materias/capas/');

		try {

			$object->save();

			$request->session()->flash('sucesso', 'Crítica alterada com sucesso.');

			return redirect()->route('painel.criticas-e-materias.index');

		} catch (\Exception $e) {

			$request->flash();

			return back()->withErrors(array('Erro ao criar Crítica! ('.$e->getMessage().')'));

		}
	}

	public function destroy(Request $request, $id)
	{
		$object = CriticasEMaterias::find($id);
		$object->delete();

		$request->session()->flash('sucesso', 'Crítica removida com sucesso.');

		return redirect()->route('painel.criticas-e-materias.index');
	}
}

laravel/app/Http/Controllers/Painel/CursosEOficinas/CursosEOficinasController.php
<?php

namespace CiaTruks\Http\Controllers\Painel\CursosEOficinas;

use Illuminate\Http\Request;
use CiaTruks\Http\Controllers\Controller;
use View;

use CiaTruks\Models\CursosEOficinas;

class CursosEOficinasController extends Controller{

	public function index()
	{
		$registros = CursosEOficinas::ordenado()->get();

		return view('painel.cursos-e-oficinas.index')->with(compact('registros'));
	}

	public function create()
	{
		return view('painel.cursos-e-oficinas.create');
	}

	public function store(Request $request)
	{
		$this->validate($request, [
      'titulo' => 'required|unique:cursos_e_oficinas'
  	]);

		$object = new CursosEOficinas;

		$object->titulo = $request->titulo;
    $object->slug = str_slug($request->titulo);
    $object->texto = $request->texto;

		try {

			$object->save();

			$request->session()->flash('sucesso', 'Curso/Oficina criado com sucesso.');

			return redirect()->route('painel.cursos-e-oficinas.index');

		} catch (\Exception $e) {

			$request->flash();

			return back()->withErrors(array('Erro ao criar Curso/Oficina! ('.$e->getMessage().')'));

		}
	}

	public function edit($id)
	{
		$registro = CursosEOficinas::find($id);

		return view('painel.cursos-e-oficinas.edit')->with(compact('registro'));
	}

	public function update(Request $request, $id)
	{
		$this->validate($request, [
        'titulo' => 'required|unique:cursos_e_oficinas,titulo,'.$id
    	]);

		$object = CursosEOficinas::find($id);

    $object->titulo = $request->titulo;
    $object->slug = str_slug($request->titulo);
    $object->texto = $request->texto;

		try {

			$object->save();

			$request->session()->flash('sucesso', 'Curso/Oficina alterado com sucesso.');

			return redirect()->route('painel.cursos-e-oficinas.index');

		} catch (\Exception $e) {

			$request->flash();

			return back()->withErrors(array('Erro ao criar Curso/Oficina! ('.$e->getMessage().')'));

		}
	}

	public function destroy(Request $request, $id)
	{
		$object = CursosEOficinas::find($id);
		$object->delete();

		$request->session()->flash('sucesso', 'Curso/Oficina removido com sucesso.');

		return redirect()->route('painel.cursos-e-oficinas.index');
	}
}

laravel/app/Http/Controllers/Painel/ImagemHome/ImagemHomeController.php
<?php

namespace CiaTruks\Http\Controllers\Painel\ImagemHome;

use Illuminate\Http\Request;
use CiaTruks\Http\Controllers\Controller;

use View;

use CiaTruks\Libs\Thumbs;
use CiaTruks\Models\ImagemHome;

class ImagemHomeController extends Controller
{
  public function index()
  {
    $registros = ImagemHome::all();

    return view('painel.imagem-home.index')->with(compact('registros'));
  }

  public function edit($id)
  {
    return view('painel.imagem-home.edit')->with('registro', ImagemHome::find($id));
  }

  public function update(Request $request, $id)
  {
    $object = ImagemHome::find($id);

    $imagem = Thumbs::make('imagem', 380, 550, 'imagem-home/');
    if($imagem) $object->imagem = $imagem;

    try {

      $object->save();

      $request->session()->flash('sucesso', 'Imagem da Home alterada com sucesso.');

      return redirect()->route('painel.imagem-home.index');

    } catch (\Exception $e) {

      $request->flash();

      return back()->withErrors(array('Erro ao alterar Imagem da Home! ('.$e->getMessage().')'));

    }
  }
}

laravel/resources/views/painel/espetaculos/create.blade.php
@extends('painel.template')

@section('conteudo')

    <div class="container-fluid padded-bottom">

    	<div class="row">
    		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

	      	<h2>Cadastrar Espetáculo</h2>

	        <hr>

	        @include('painel.partials.mensagens')

		    </div>
		  </div>

      <form action="{{ URL::route('painel.espetaculos.store') }}" method="post" enctype="multipart/form-data">

  			{!! csrf_field() !!}

  			<div class="row">
  				<div class="col-xs-12 col-sm-10 col-md-10 col-lg-6">

            <div class="form-group">
  						<label for="inputTitulo">Título</label>
  						<input type="text" name="titulo" class="form-control" id="inputTitulo" value="{{old('titulo')}}">
  					</div>

  			    <div class="form-group">
  						<label for="inputTexto">Texto</label>
  						<textarea name="texto" class="form-control" id="inputTexto">{{old('texto')}}</textarea>
  					</div>

            <div class="form-group">
  						<label for="inputFichaTecnica">Ficha Técnica</label>
  						<textarea name="ficha_tecnica" class="form-control textarea-simples" id="inputFichaTecnica">{{old('ficha_tecnica')}}</textarea>
  					</div>

  					<div class="form-group">
  						@if(old('imagem'))
  							Imagem de Capa atual<br>
  							<img src="assets/img/espetaculos/capas/{{old('imagem')}}"><br>
  						@endif
  						<label for="inputImagem">Imagem de Capa</label>
  						<input type="file" class="form-control" id="inputImagem" name="imagem">
  					</div>

            @include('painel.partials.upload-imagens')

            @include('painel.partials.form-videos')

  				</div>
  			</div>

			  <button type="submit" title="Cadastrar" class="btn btn-success">Cadastrar</button>

			  <a href="{{ URL::route('painel.espetaculos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

	  	</form>

    </div>

@endsection

laravel/resources/views/painel/espetaculos/edit.blade.php
@extends('painel.template')

@section('conteudo')

  <div class="container-fluid padded-bottom">

    <div class="row">
    	<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

		  	<h2>Editar Espetáculo</h2>

		    <hr>

		    @include('painel.partials.mensagens')

		  </div>
		</div>

    <form action="{{ URL::route('painel.espetaculos.update', $registro->id) }}" method="post" enctype="multipart/form-data">

			<input type="hidden" name="_method" value="PUT">

			{!! csrf_field() !!}

			<div class="row">
				<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

          <div class="form-group">
            <label for="inputTitulo">Título</label>
            <input type="text" name="titulo" class="form-control" id="inputTitulo" value="{{$registro->titulo}}">
          </div>

			    <div class="form-group">
						<label for="inputTexto">Texto</label>
						<textarea name="texto" class="form-control" id="inputTexto">{{$registro->texto}}</textarea>
					</div>

          <div class="form-group">
            <label for="inputFichaTecnica">Ficha Técnica</label>
            <textarea name="ficha_tecnica" class="form-control textarea-simples" id="inputFichaTecnica">{{$registro->ficha_tecnica}}</textarea>
          </div>

					<div class="form-group">
						@if($registro->imagem)
							Imagem Atual<br>
							<img src="assets/img/espetaculos/capas/{{$registro->imagem}}"><br>
						@endif
						<label for="inputImagem">Trocar Imagem</label>
						<input type="file" class="form-control" id="inputImagem" name="imagem">
					</div>

          @include('painel.partials.upload-imagens')

          @include('painel.partials.form-videos')

				</div>
			</div>

			<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

			<a href="{{ URL::route('painel.espetaculos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

		</form>

    </div>

@endsection

laravel/resources/views/painel/espetaculos/index.blade.php
@extends('painel.template')

@section('conteudo')

  <div class="container-fluid padded-bottom">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <h2>Espetáculos</h2>

        <hr>

      	@include('painel.partials.mensagens')

        <a href="{{ URL::route('painel.espetaculos.create') }}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus-sign"></span> Adicionar Espetáculo</a>

        <table class="table table-striped table-bordered table-hover">

          <thead>
          	<tr>
          		<th>Título</th>
              <th>Texto</th>
              <td><span class="glyphicon glyphicon-list-alt"></span></td>
          		<th><span class="glyphicon glyphicon-cog"></span></th>
          	</tr>
        	</thead>

        	<tbody>
          	@foreach ($registros as $registro)

            	<tr class="tr-row">
                <td>{{$registro->titulo}}</td>
            		<td>
                  {{ str_words(strip_tags($registro->texto), 15)  }}
                </td>
                <td>
                  <a href="{{ route('painel.comentarios-da-imprensa.index', ['espetaculos_id' => $registro->id]) }}" class="btn btn-default btn-sm">comentários da imprensa</a>
                </td>
            		<td class="crud-actions">
              		<a href="{{ URL::route('painel.espetaculos.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>

                  <form action="{{ URL::route('painel.espetaculos.destroy', $registro->id) }}" method="post">
                    {!! csrf_field() !!}
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
                  </form>
            		</td>
            	</tr>

          	@endforeach
        	</tbody>

      	</table>

      </div>
    </div>
  </div>

@endsection